
export enum PersonTypeEnum {
    RESIDENT = 'RESIDENT',
    MILITARY = 'MILITARY',
    FOREIGN_RESIDENT = 'FOREIGN_RESIDENT',
    FOREIGNER = 'FOREIGNER',
    WITHOUT_CITIZENSHIP = 'WITHOUT_CITIZENSHIP',
}